1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

NumPy (Numerical Python) is a core library in Python used for numerical and scientific computing. It provides support for arrays, matrices, and various mathematical functions, making complex data manipulations easy and efficient.

Advantages of NumPy:

Array-based operations: It supports multi-dimensional arrays (ndarrays) that enable large data structures to be managed efficiently.
Memory efficiency: NumPy arrays consume less memory than Python lists, which improves performance, especially for large datasets.
Speed: Operations on NumPy arrays are much faster than similar operations on lists due to optimized algorithms and lower-level implementations.
Vectorized operations: Mathematical and logical operations can be performed on entire arrays without the need for explicit loops.
Interoperability: It integrates seamlessly with other libraries like Pandas, SciPy, and Matplotlib, enhancing data analysis capabilities.



2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?


np.mean(): Calculates the arithmetic mean (average) of elements across an array or specified axis. It does not allow weighted calculations.
np.average(): Also calculates the mean but has an option to specify weights for elements, enabling a weighted average calculation.
Use np.mean() for a simple average of values, and np.average() when you need to apply weights to different values.


3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

1D Array: Use slicing ([::-1]) to reverse a 1D array.


arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d[::-1])   

2D Array: Use np.flip() with an axis parameter to reverse along specific axes.

Horizontal Flip (reverse rows): np.flip(arr, axis=1)
Vertical Flip (reverse columns): np.flip(arr, axis=0)

arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
print(np.flip(arr_2d, axis=1))  
print(np.flip(arr_2d, axis=0))


4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.


Use arr.dtype to check the data type of elements in a NumPy array.
Importance of Data Types:
Memory efficiency: Specifying smaller data types (e.g., int8 instead of int64) saves memory.
Performance: Proper data types reduce processing time for operations, especially on large datasets.

arr = np.array([1, 2, 3], dtype=np.int32)
print(arr.dtype)


5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

An ndarray (n-dimensional array) is the core data structure in NumPy for holding homogeneous data.

Key Features:
Fixed size: Once created, the size of an ndarray cannot be changed.
Multidimensional: Supports multi-dimensional arrays, allowing for complex data structures.
Efficient operations: ndarrays allow element-wise and vectorized operations, improving computation speed.
Differentiation from lists: Unlike Python lists, ndarrays store elements in continuous memory blocks, making them faster for numerical operations.


6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

NumPy arrays are optimized for numerical computations because they:
Have contiguous memory allocation: Reduces the overhead seen in Python lists, which are pointers to separate objects.
Support vectorized operations: Minimize the need for loops in Python, thus reducing execution time.
Allow better cache utilization: CPU cache is used more efficiently, speeding up repeated accesses.


7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

vstack(): Stacks arrays vertically (row-wise).
hstack(): Stacks arrays horizontally (column-wise).
Example:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

.....Vertical stack
print(np.vstack((arr1, arr2)))
....Horizontal stack
print(np.hstack((arr1, arr2)))


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

fliplr(): Flips an array along the left-right axis (columns). Used for 2D arrays or higher.
flipud(): Flips an array along the up-down axis (rows). Also for 2D or higher dimensions.
Example:
arr = np.array([[1, 2], [3, 4], [5, 6]])
....Left-right flip
print(np.fliplr(arr))
....Up-down flip
print(np.flipud(arr))


9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

array_split() divides an array into specified subarrays, even if the split is uneven. It ensures that all sections are created, with some sections possibly having fewer elements.

Example:
arr = np.array([1, 2, 3, 4, 5])
print(np.array_split(arr, 3))

10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

Vectorization: Allows operations on entire arrays without explicit loops, enhancing speed and code simplicity.
Broadcasting: Lets arrays with different shapes interact in element-wise operations by “stretching” smaller arrays to match the shape of the larger array.
Example:
arr = np.array([1, 2, 3])
print(arr + 5)

In [ ]:
#practical Q
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np
a=np.random.randint(1,100,(3,3))
a

array([[88,  7, 60],
       [ 7, 91, 77],
       [59, 27, 41]])

In [ ]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
b=np.arange(10)
b
c=b.reshape(2,5)
c
d=b.reshape(5,2)
d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [44]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
a=np.random.rand(4,4)
a
b=np.pad((a),pad_width=1)
b


array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.69563121, 0.95650135, 0.47394604, 0.49231318,
        0.        ],
       [0.        , 0.08266519, 0.39110991, 0.35769008, 0.98332544,
        0.        ],
       [0.        , 0.14847322, 0.19525691, 0.09116887, 0.581989  ,
        0.        ],
       [0.        , 0.94747112, 0.10569251, 0.81677241, 0.57106461,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [ ]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
a=np.arange(10,60,5)
a

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [ ]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.
a=np.array(['python', 'numpy', 'pandas'])
print(a)
b=np.char.upper(a)
print("Uppercase",b)
c=np.char.lower(a)
print("Lowercase",c)
d=np.char.title(a)
print("titlecase",d)

['python' 'numpy' 'pandas']
Uppercase ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase ['python' 'numpy' 'pandas']
titlecase ['Python' 'Numpy' 'Pandas']


In [ ]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
a=np.array(['python', 'numpy', 'pandas'])
a
b=np.char.join(' ',a)
b

array(['p y t h o n', 'n u m p y', 'p a n d a s'], dtype='<U11')

In [ ]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
a=np.array([[1,2,3],[4,5,6]])
a
b=np.array([[7,8,9],[10,11,12]])
b
c=np.add(a,b)
print("addition",c)
d=np.subtract(a,b)
print("subtraction",d)
e=np.multiply(a,b)
print("multiplication",e)
f=np.divide(a,b)
print("division",f)

addition [[ 8 10 12]
 [14 16 18]]
subtraction [[-6 -6 -6]
 [-6 -6 -6]]
multiplication [[ 7 16 27]
 [40 55 72]]
division [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [43]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements
a=np.identity(5)
a
b=np.diag(a)
b

array([1., 1., 1., 1., 1.])

In [41]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
a=np.random.randint(0,1000,100)
a
for i in a:
  if i>1:
    for j in range(2,i):
      if i%j==0:
        break
      else:
        print(i)
        break


905
105
771
927
43
889
681
441
761
417
251
285
359
595
229
347
409
277
519
573
805
151
791
793
983
871
35
997
961
549
689
685
665
379
185
423
231
613
153
819
621
37
331
439
891
311
653
33
973
695
683
131


In [45]:
# 10. Create a NumPy array representing daily temperatures for a month.
# Calculate and display the weekly averages
temp=np.random.randint(15,35,size=30)
temp
weekly_averages = []
for i in range(0, 30, 7):
  week_temps =temp[i:min(i + 7, 30)]
  weekly_average = np.mean(week_temps)
  weekly_averages.append(weekly_average)

print("Weekly Average Temperatures:")
for i, avg in enumerate(weekly_averages):
  print(f"Week {i+1}: {avg:.2f}")

Weekly Average Temperatures:
Week 1: 23.71
Week 2: 26.57
Week 3: 26.29
Week 4: 27.71
Week 5: 27.00
